# Generated by Django 3.2 on 2023-09-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_rename_category_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genrestitles',
            old_name='genre',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='genrestitles',
            old_name='titles',
            new_name='titles_id',
        ),
    ]
