# Generated by Django 3.2 on 2023-09-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20230904_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genrestitles',
            old_name='titles_id',
            new_name='title_id',
        ),
    ]
